// The creatures, in the order the sheet shows them, with what the sheet says about each.
// size is the battle size class (S, M, L, or F for flyers); the limits are in CLAUDE.md and src/preview/main.js.
import { emberwolf } from './emberwolf.js';
import { tidefang } from './tidefang.js';
import { thornstag } from './thornstag.js';
import { stonemaul } from './stonemaul.js';
import { wardshell } from './wardshell.js';
import { pyrewing } from './pyrewing.js';
import { eagle } from './eagle.js';
import { lion } from './lion.js';
import { elephant } from './elephant.js';
import { panda } from './panda.js';
import { owl } from './owl.js';

export const INFO = {
  emberwolf: { name: 'Emberwolf', element: 'Fire', size: 'M', build: emberwolf, note: 'A heavy-shouldered wolf whose fire lives in its coat.',
    parts: ['<b>Body.</b> Deep chest, tucked waist, bent hind legs on hocks, toes and claws.', '<b>Coat.</b> Blue-grey, a shade darker along the back, cream on the chest and belly. Soft overlapping locks of fur make the ruff, cheeks, chest fringe, spine and tail, darker at the root and paler at the tip.', '<b>Face.</b> Round amber eyes with a catchlight under a soft brow, a jaw that breathes a little open on two fangs and a tongue.', '<b>Fire.</b> A mane of layered flame from crown to back, a burning tail, ember veins, rising sparks and firelight on its own fur.'] },
  tidefang: { name: 'Tidefang', element: 'Water', size: 'L', build: tidefang, note: 'A heavy armoured crocodile carrying the sea in crystal, high on its arms, jaws wide.',
    parts: ['<b>Body.</b> Long, deep and round-bellied, carried high on muscled arms with elbow knuckles, scutes up the back of each limb and a small crystal at every elbow. Webbed feet: five clawed toes in front, four behind.', '<b>Armour.</b> Keeled scutes in rows, a double crest down a shorter tail, dark bands across a deep teal back, a pale belly.', '<b>Face.</b> A big deep head, eye turrets with glowing eyes, a bulb nose, and an interlocking jaw with two long fangs a side.', '<b>Crystal.</b> Glowing clusters down the spine and a crystal fan at the tail, all pulsing together, and wave lines on each flank.'] },
  thornstag: { name: 'Thornstag', element: 'Grass', size: 'M', build: thornstag, note: 'A gentle forest stag whose antler crown blooms with living green light.',
    parts: ['<b>Body.</b> A deep barrel of ribs, a tucked flank, strong shoulders and thighs, long legs with knees and hocks on cloven hooves, a short raised tail fringed with locks.', '<b>Coat.</b> Warm fawn, a shade darker along the back, cream on the belly, throat and rump, with a mantle of moss and grass down the spine and a vine wound round the neck.', '<b>Face.</b> Round hazel eyes under a soft fawn brow, large ears that flick, and a long muzzle closed in a calm line.', '<b>Bloom.</b> An antler crown fanned wide and low in the side plane, green veins of light along the beams, and a bloom of leaves, glowing leaves and buds on every tip, the shape that says Grass from the side; leaves of light drift round it and seeds rise.', '<b>Thorns.</b> Its attack lowers the crown and tosses it up through the target; its ultimate bursts a ring of glowing thorns from the ground at its forefeet.'] },
  stonemaul: { name: 'Stonemaul', element: 'Ground', size: 'L', build: stonemaul, note: 'A huge bear in stone and iron, stone spires cracked with amber light along its hump, claws as weapons.',
    parts: ['<b>Body.</b> A great shoulder hump, a deep barrel chest, pillar forelegs and a heavy rump under a thick ruff.', '<b>Spires.</b> Jagged stone spires along the hump, cracked with amber light and burning at the points, the shape that says Ground from the side.', '<b>Armour.</b> Stone gauntlets with iron bands and spikes and slimmer stone pauldrons, lined with amber rune light.', '<b>Claws.</b> Four steel claws on each forepaw, long and hooked down.', '<b>Face.</b> Round honey eyes under a soft brow of fur, a mouth just open on two small fangs.'] },
  wardshell: { name: 'Wardshell', element: 'Water', size: 'L', build: wardshell, note: 'A deep-sea tortoise, its domed shell crested with breaking waves, its wards rising when it is struck.',
    parts: ['<b>Shell.</b> A high dark dome of raised hexagonal plates with sunken seams, a gold rim with stone spikes, and a line of water light rippling round it.', '<b>Crest.</b> Four breaking waves along the spine of the shell, dark fins with crests of glowing water, the shape that says Water from the side.', '<b>Body.</b> Pillar legs in stone shin plates and gold bands with blunt nails, a short spiked tail, a neck that reaches out from a gold collar.', '<b>Face.</b> A big heavy head, stern brow scutes over amber eyes, a hooked beak that snaps, and a water gem on the crown.', '<b>Wards.</b> Six shields of water light that rise and circle it when it is struck, and swirl round it in its ultimate.'] },
  pyrewing: { name: 'Pyrewing', element: 'Fire', size: 'F', build: pyrewing, note: 'A young phoenix hovering on raised wings, warm red-orange with a golden breast, a crest and tail of living flame.',
    parts: ['<b>Body.</b> A plump, deep-chested teardrop with a round breast of small layered feathers, feathered thighs, and golden shins drawn up under it with three ivory talons forward and one back.', '<b>Plumage.</b> Red-orange, a shade deeper along the back and warmer orange low on the flanks, with a golden cream breast and belly. The wing and tail feathers run from deep red at the quill to golden tips.', '<b>Face.</b> A big round head with round amber eyes on pale golden patches, a soft brow and a small hooked golden beak that can open.', '<b>Fire.</b> A crest of three plumes swept back from the crown, each tipped with flame; flames along the back, burning tips on the longest flight feathers, three streamers of flame for a tail, sparks drifting off it and firelight on its own feathers.', '<b>Strike.</b> It attacks with a diving swoop, raking talons and a fiery swipe. Its ultimate is ranged: it rears in a sunburst of flame and flings a volley of burning feathers at the target.'] },
  eagle: { name: 'Stormtalon', element: 'Electric', size: 'F', build: eagle, note: 'A storm eagle hovering on raised wings, a crest of lightning crackling on its crown.',
    parts: ['<b>Body.</b> A deep chest held high and the tail end dropping as it hangs in the air; short yellow legs in feathered trousers, talons curled under.', '<b>Wings.</b> Raised high in a V with the hands swept back and fingered tips, warm brown paling to buff at the edges, beating slowly; a lightning vein runs down each one.', '<b>Face.</b> A big round white head, round golden eyes that blink, and a short yellow hooked beak that opens.', '<b>Storm.</b> A crest of lightning plumes fanned back from the crown, the shape that says Electric from the side; arcs crackle round the bird and sparks jump off it. Its attack dives and throws the talons forward in a burst of sparks; its ultimate calls a bolt down from the sky onto its target.'] },
  lion: { name: 'Sunmane', element: 'Light', size: 'L', build: lion, note: 'A lion braced to pounce, its mane crowned with a corona of sunfire, claws ready.',
    parts: ['<b>Mane.</b> Three rings of clumped locks swept back toward the shoulders, warm brown at the root and honey at the tip, longest on the crest, with a beard and a cape along the spine.', '<b>Corona.</b> A sunburst over the mane: an arc of light from brow to nape with long and short rays fanning out of it, the shape that says Light from across the field.', '<b>Body.</b> A tawny golden coat with a cream belly over a deep chest, heavy shoulders and haunches, sun glyphs burning under the fur, and a tufted tail with a spark of sun at its tip.', '<b>Face.</b> Round amber eyes under a soft golden brow, a jaw just open on two small fangs.', '<b>Strike.</b> Its attack rears up and swipes the right forepaw through, four long claws out, with three golden slashes that flare as it lands.'] },
  elephant: { name: 'Grandtusk', element: 'Ice', size: 'L', build: elephant, note: 'A woolly mammoth in a shaggy frost-tipped coat, ice ridged along its hump, tusks rimed with frost.',
    parts: ['<b>Coat.</b> A warm mid-brown coat over a vast barrel and a high shoulder hump, with a skirt of long shaggy locks round the belly and legs, lighter at the tips, and frost veins glowing under the fur.', '<b>Ridge.</b> A row of ice crystals along the hump and back, leaning back, the shape that says Ice from the side.', '<b>Tusks.</b> Great ivory spirals curving up and in, banded with frost, their points rimed with glowing ice and small crystals.', '<b>Face.</b> A high domed skull, small furred ears, round ice-blue eyes under a soft brow, a frost rune on the brow, and an eight-joint trunk furred at the root.'] },
  panda: { name: 'Ironpaw', element: 'Neutral', size: 'S', build: panda, note: 'A panda fighter in a low guard, fists up and wrapped, white qi burning off its shoulders.',
    parts: ['<b>Guard.</b> A low, wide stance on planted black legs, the right fist leading and the left held back at the chin, forearms wrapped in red, fists bound in cream with gold knuckle plates.', '<b>Qi.</b> Pale flames of qi rising off the shoulders and back along the top line, qi lines burning on the chest and forearms, a glow and sparks round each fist.', '<b>Face.</b> A heavy round head, black patches with slit eyes under a black brow, a snarl with fangs, and a red headband with a gold plate and two tails that stream behind.', '<b>Strike.</b> Its attack swings the lead arm up level and snaps the elbow straight into a punch; its ultimate throws a left and then a right.'] },
  owl: { name: 'Duskseer', element: 'Dark', size: 'S', build: owl, note: 'A horned owl of the night, stern under a V brow, a crest of shadow quills burning violet.',
    parts: ['<b>Face.</b> A pale heart-shaped disc, amber eyes under a stern black V brow, a hooked beak that opens, tall ear tufts tipped with violet; the head rests turned toward the camera, as an owl\'s does.', '<b>Crest.</b> Shadow quills fanned from crown to nape, violet with pale cores, the shape that says Dark from the side.', '<b>Plumage.</b> Near-black indigo on the back, a muted lavender breast of barred scale-feathers, wings folded down the sides with a violet crescent and rune lines on each, a short dark tail.', '<b>Stance.</b> Upright on short feathered legs, three hooked talons forward and one back, motes of starlight drifting round it.'] },
};

export const ORDER = ['emberwolf', 'tidefang', 'thornstag', 'stonemaul', 'wardshell', 'pyrewing', 'eagle', 'lion', 'elephant', 'panda', 'owl'];
