// The creatures, in the order the sheet shows them, with what the sheet says about each.
// size is the battle size class (S, M, L, or F for flyers); the limits are in CLAUDE.md and src/preview/main.js.
import { emberwolf } from './emberwolf.js';
import { tidefang } from './tidefang.js';
import { thornstag } from './thornstag.js';
import { stonemaul } from './stonemaul.js';
import { wardshell } from './wardshell.js';
import { pyrewing } from './pyrewing.js';
import { eagle } from './eagle.js';
import { lion } from './lion.js';
import { elephant } from './elephant.js';
import { panda } from './panda.js';
import { owl } from './owl.js';

export const INFO = {
  emberwolf: { name: 'Emberwolf', element: 'Fire', size: 'M', build: emberwolf, note: 'A heavy-shouldered wolf whose fire lives in its coat.',
    parts: ['<b>Body.</b> Deep chest, tucked waist, bent hind legs on hocks, toes and claws.', '<b>Coat.</b> Dark along the back, pale on the chest and belly. Soft overlapping locks of fur make the ruff, cheeks, chest fringe, spine and tail, darker at the root and paler at the tip.', '<b>Face.</b> Heavy brow, glowing slit eyes that blink, a jaw that breathes open on fangs and a tongue.', '<b>Fire.</b> A mane of layered flame from crown to back, a burning tail, ember veins, rising sparks and firelight on its own fur.'] },
  tidefang: { name: 'Tidefang', element: 'Water', size: 'L', build: tidefang, note: 'A heavy, armoured crocodile carrying the sea in crystal.',
    parts: ['<b>Body.</b> Long, deep and round-bellied, carried high on arms with shoulder and hip muscle, elbow knuckles, scutes up the back of each limb and a small crystal at every elbow. Webbed feet: five clawed toes in front, four behind.', '<b>Armour.</b> Keeled scutes in rows, a double crest down the tail, dark bands across the back, a pale belly.', '<b>Face.</b> Eye turrets with glowing eyes, a bulb nose, an interlocking jaw with two long fangs a side, and a deeper head to match the body.', '<b>Crystal.</b> Glowing clusters down the spine and a crystal fan at the tail, pulsing light onto its own scales, wave lines on each flank.'] },
  thornstag: { name: 'Thornstag', element: 'Grass', size: 'M', build: thornstag, note: 'A tall, gentle stag that the forest grows on, kind in the face and mighty in the shoulder.',
    parts: ['<b>Body.</b> A barrel of ribs, a tucked flank, withers and hips that rise, built shoulders and thighs, a crest of neck muscle. Slim legs with knees and hocks, cloven hooves, a soft throat ruff and a raised tail, cream beneath and tipped with a leaf sprig.', '<b>Coat.</b> Warm brown with a dark stripe down the spine, cream below, fawn spots over the flanks and haunches.', '<b>Face.</b> Large leaf ears that flick, wide soft eyes and a long muzzle closed in a small smile. No fangs.', '<b>Magic.</b> Great antlers in leaf and blossom with a glow behind them, leaves and petals turning round the crown, vines and blossoms at the neck, a leaf emblem on the chest, a moss mantle, rune light and fireflies.'] },
  stonemaul: { name: 'Stonemaul', element: 'Ground', size: 'L', build: stonemaul, note: 'A huge mountain bear in stone and iron, roaring, whose claws are its weapons.',
    parts: ['<b>Body.</b> A great shoulder hump, a deep barrel chest, pillar forelegs and a heavy rump, under a thick ruff of fur.', '<b>Claws.</b> Four steel claws on each forepaw, as long as a forearm and hooked down like blades.', '<b>Armour.</b> Stone gauntlets with iron bands and spikes, stone pauldrons with iron spikes, plates down the hump, all lined with amber rune light.', '<b>Face.</b> A roaring mouth with thick canines, small glowing eyes under angry brows.', '<b>Aura.</b> Two turning rings of rune light on the ground, rocks circling the bear, amber haze and rising motes.'] },
  wardshell: { name: 'Wardshell', element: 'Water', size: 'L', build: wardshell, note: 'A sturdy tortoise with a plated shell, calm and hard to move, guarded by shields that circle it.',
    parts: ['<b>Shell.</b> A dome of raised hexagonal plates with sunken seams, a gold rim with spikes, a sigil and glowing gem at the crown, and a patch of moss and blossoms on one shoulder.', '<b>Legs.</b> Four thick pillars in stone shin plates and gold bands, with blunt nails.', '<b>Face.</b> A calm, noble head: a domed brow with a small stone crest, big golden eyes under heavy lids, a hooked beak and a closed mouth turned up at the corners.', '<b>Ward.</b> Eight shields of light circle the whole body, with a faint ring of light on their path.'] },
  pyrewing: { name: 'Pyrewing', element: 'Fire', size: 'F', build: pyrewing, note: 'A phoenix on the wing, with feathers that run from crimson to gold and burn at the tips.',
    parts: ['<b>Wings.</b> Wide wings in layered feathers, hinged at the arm, forearm and hand so the tips follow the beat a moment late, with flame on the longest feathers.', '<b>Tail.</b> Seven long tail feathers and two streamers, each burning at the end.', '<b>Face.</b> A hooked beak, burning white-gold eyes, a crest of plumes with a crown of flame.', '<b>Fire.</b> Flames burn along the back, the neck, the shoulders, the thighs and the tail root, with a swirl of sparks round the bird and a warm glow behind it.'] },
  eagle: { name: 'Stormtalon', element: 'Electric', size: 'F', build: eagle, note: 'An eagle riding the wind, wings wide and eyes fixed on something far below.',
    parts: ['<b>Wings.</b> Broad wings with the fingered tips of a true eagle, in dark brown that pales to gold at the edge, beating slowly with the tips following a moment behind.', '<b>Head.</b> A white head with a heavy brow, a keen amber eye and a great hooked beak, a golden nape and a white ruff.', '<b>Talons.</b> Yellow legs thrust forward with the talons spread and hooked, ready to strike.', '<b>Wind.</b> Pale ribbons of wind circle the bird, and bright specks drift in its wake.'] },
  lion: { name: 'Sunmane', element: 'Light', size: 'L', build: lion, note: 'A lion braced to pounce, its mane a corona of sunfire, roaring with its claws out.',
    parts: ['<b>Mane.</b> Three rings of clumped locks swept back toward the shoulders, dark at the root and gold at the tip, longest on the crest, with a beard and a cape along the spine.', '<b>Corona.</b> A sunburst over the mane: an arc of light from brow to nape with long and short rays fanning out of it, the shape that says Light from across the field.', '<b>Body.</b> A dark umber coat over a deep chest, heavy shoulders and haunches, sun glyphs burning under the fur, and a tufted tail with a spark of sun at its tip.', '<b>Face.</b> A roaring mouth with thick canines, slit amber eyes under a heavy brow.', '<b>Strike.</b> Its attack rears up and swipes the right forepaw through, four long claws out, with three golden slashes that flare as it lands.'] },
  elephant: { name: 'Grandtusk', element: 'Ice', size: 'L', build: elephant, note: 'A giant elephant with tusks as long as its body is deep, wise and slow to anger.',
    parts: ['<b>Tusks.</b> Thick curved ivory, banded in gold at the base, each with a glowing gem.', '<b>Trunk.</b> Eight joints, so it sways and curls in a slow wave.', '<b>Body.</b> A vast barrel with pillar legs and wide feet, wrinkled grey skin, and ears like sails that flap.', '<b>Face.</b> A great dome of a brow, small kind eyes, and a rune of light on the forehead.'] },
  panda: { name: 'Ironpaw', element: 'Neutral', size: 'S', build: panda, note: 'A panda warrior in a wide stance, one fist thrown and the other drawn back.',
    parts: ['<b>Fists.</b> The right arm drives forward in wrapped knuckles, with gold qi at the fist and bands of light flying off it. The left fist rests drawn back at the hip.', '<b>Stance.</b> A wide horse stance on black legs, a black belt with a gold buckle and red sash tails.', '<b>Face.</b> Black patches and ears, brows pulled down, a shouting mouth, and a red headband with a gold plate and two tails that stream behind.', '<b>Build.</b> A round, heavy trunk with a black shoulder band.'] },
  owl: { name: 'Duskseer', element: 'Dark', size: 'S', build: owl, note: 'A wise owl on a mossy branch, awake while the world sleeps.',
    parts: ['<b>Face.</b> A heart of pale feathers round huge golden eyes, a small hooked beak and two ear tufts, on a head that turns far round.', '<b>Plumage.</b> A chest of barred scale-feathers, wings folded down the sides, a short barred tail.', '<b>Perch.</b> Talons gripping a forked, mossy branch held up by a root.', '<b>Night.</b> A crescent moon behind, stars that drift, and a ring of rune light turning on the ground.'] }
};

export const ORDER = ['emberwolf', 'tidefang', 'thornstag', 'stonemaul', 'wardshell', 'pyrewing', 'eagle', 'lion', 'elephant', 'panda', 'owl'];
