// The creatures, in the order the sheet shows them, with what the sheet says about each.
// size is the battle size class (S, M, L, or F for flyers); the limits are in CLAUDE.md and src/preview/main.js.
import { emberwolf } from './emberwolf.js';
import { tidefang } from './tidefang.js';
import { thornstag } from './thornstag.js';
import { stonemaul } from './stonemaul.js';
import { wardshell } from './wardshell.js';
import { pyrewing } from './pyrewing.js';
import { eagle } from './eagle.js';
import { lion } from './lion.js';
import { elephant } from './elephant.js';
import { panda } from './panda.js';
import { owl } from './owl.js';

export const INFO = {
  emberwolf: { name: 'Emberwolf', element: 'Fire', size: 'M', build: emberwolf, note: 'A heavy-shouldered wolf whose fire lives in its coat.',
    parts: ['<b>Body.</b> Deep chest, tucked waist, bent hind legs on hocks, toes and claws.', '<b>Coat.</b> Dark along the back, pale on the chest and belly. Soft overlapping locks of fur make the ruff, cheeks, chest fringe, spine and tail, darker at the root and paler at the tip.', '<b>Face.</b> Heavy brow, glowing slit eyes that blink, a jaw that breathes open on fangs and a tongue.', '<b>Fire.</b> A mane of layered flame from crown to back, a burning tail, ember veins, rising sparks and firelight on its own fur.'] },
  tidefang: { name: 'Tidefang', element: 'Water', size: 'L', build: tidefang, note: 'A heavy, armoured crocodile carrying the sea in crystal.',
    parts: ['<b>Body.</b> Long, deep and round-bellied, carried high on arms with shoulder and hip muscle, elbow knuckles, scutes up the back of each limb and a small crystal at every elbow. Webbed feet: five clawed toes in front, four behind.', '<b>Armour.</b> Keeled scutes in rows, a double crest down the tail, dark bands across the back, a pale belly.', '<b>Face.</b> Eye turrets with glowing eyes, a bulb nose, an interlocking jaw with two long fangs a side, and a deeper head to match the body.', '<b>Crystal.</b> Glowing clusters down the spine and a crystal fan at the tail, pulsing light onto its own scales, wave lines on each flank.'] },
  thornstag: { name: 'Thornstag', element: 'Grass', size: 'M', build: thornstag, note: 'A tall, gentle stag that the forest grows on, kind in the face and mighty in the shoulder.',
    parts: ['<b>Body.</b> A barrel of ribs, a tucked flank, withers and hips that rise, built shoulders and thighs, a crest of neck muscle. Slim legs with knees and hocks, cloven hooves, a soft throat ruff and a raised tail, cream beneath and tipped with a leaf sprig.', '<b>Coat.</b> Warm brown with a dark stripe down the spine, cream below, fawn spots over the flanks and haunches.', '<b>Face.</b> Large leaf ears that flick, wide soft eyes and a long muzzle closed in a small smile. No fangs.', '<b>Magic.</b> Great antlers in leaf and blossom with a glow behind them, leaves and petals turning round the crown, vines and blossoms at the neck, a leaf emblem on the chest, a moss mantle, rune light and fireflies.'] },
  stonemaul: { name: 'Stonemaul', element: 'Ground', size: 'L', build: stonemaul, note: 'A huge bear in stone and iron, stone spires cracked with amber light along its hump, claws as weapons.',
    parts: ['<b>Body.</b> A great shoulder hump, a deep barrel chest, pillar forelegs and a heavy rump under a thick dark ruff.', '<b>Spires.</b> Jagged stone spires along the hump, cracked with amber light and burning at the points, the shape that says Ground from the side.', '<b>Armour.</b> Stone gauntlets with iron bands and spikes and slimmer stone pauldrons, lined with amber rune light.', '<b>Claws.</b> Four steel claws on each forepaw, as long as a forearm and hooked down like blades.', '<b>Face.</b> A roaring mouth with thick canines, slit amber eyes under heavy angry brows.'] },
  wardshell: { name: 'Wardshell', element: 'Water', size: 'L', build: wardshell, note: 'A deep-sea tortoise, its domed shell crested with breaking waves, its wards rising when it is struck.',
    parts: ['<b>Shell.</b> A high dark dome of raised hexagonal plates with sunken seams, a gold rim with stone spikes, and a line of water light rippling round it.', '<b>Crest.</b> Four breaking waves along the spine of the shell, dark fins with crests of glowing water, the shape that says Water from the side.', '<b>Body.</b> Pillar legs in stone shin plates and gold bands with blunt nails, a short spiked tail, a neck that reaches out from a gold collar.', '<b>Face.</b> A big heavy head, stern brow scutes over amber eyes, a hooked beak that snaps, and a water gem on the crown.', '<b>Wards.</b> Six shields of water light that rise and circle it when it is struck, and swirl round it in its ultimate.'] },
  pyrewing: { name: 'Pyrewing', element: 'Fire', size: 'F', build: pyrewing, note: 'A phoenix on the wing, with feathers that run from crimson to gold and burn at the tips.',
    parts: ['<b>Wings.</b> Wide wings in layered feathers, hinged at the arm, forearm and hand so the tips follow the beat a moment late, with flame on the longest feathers.', '<b>Tail.</b> Seven long tail feathers and two streamers, each burning at the end.', '<b>Face.</b> A hooked beak, burning white-gold eyes, a crest of plumes with a crown of flame.', '<b>Fire.</b> Flames burn along the back, the neck, the shoulders, the thighs and the tail root, with a swirl of sparks round the bird and a warm glow behind it.'] },
  eagle: { name: 'Stormtalon', element: 'Electric', size: 'F', build: eagle, note: 'An eagle riding the wind, wings wide and eyes fixed on something far below.',
    parts: ['<b>Wings.</b> Broad wings with the fingered tips of a true eagle, in dark brown that pales to gold at the edge, beating slowly with the tips following a moment behind.', '<b>Head.</b> A white head with a heavy brow, a keen amber eye and a great hooked beak, a golden nape and a white ruff.', '<b>Talons.</b> Yellow legs thrust forward with the talons spread and hooked, ready to strike.', '<b>Wind.</b> Pale ribbons of wind circle the bird, and bright specks drift in its wake.'] },
  lion: { name: 'Sunmane', element: 'Light', size: 'L', build: lion, note: 'A lion braced to pounce, its mane a corona of sunfire, roaring with its claws out.',
    parts: ['<b>Mane.</b> Three rings of clumped locks swept back toward the shoulders, dark at the root and gold at the tip, longest on the crest, with a beard and a cape along the spine.', '<b>Corona.</b> A sunburst over the mane: an arc of light from brow to nape with long and short rays fanning out of it, the shape that says Light from across the field.', '<b>Body.</b> A dark umber coat over a deep chest, heavy shoulders and haunches, sun glyphs burning under the fur, and a tufted tail with a spark of sun at its tip.', '<b>Face.</b> A roaring mouth with thick canines, slit amber eyes under a heavy brow.', '<b>Strike.</b> Its attack rears up and swipes the right forepaw through, four long claws out, with three golden slashes that flare as it lands.'] },
  elephant: { name: 'Grandtusk', element: 'Ice', size: 'L', build: elephant, note: 'A woolly mammoth in a shaggy frost-tipped coat, ice ridged along its hump, tusks rimed with frost.',
    parts: ['<b>Coat.</b> A near-black brown coat over a vast barrel and a high shoulder hump, with a skirt of long shaggy locks round the belly and legs, frosted at the tips, and frost veins glowing under the fur.', '<b>Ridge.</b> A row of ice crystals along the hump and back, leaning back, the shape that says Ice from the side.', '<b>Tusks.</b> Great ivory spirals curving up and in, banded with frost, their points rimed with glowing ice and small crystals.', '<b>Face.</b> A high domed skull, small furred ears, heavy brows over pale ice eyes, a frost rune on the brow, and an eight-joint trunk furred at the root.'] },
  panda: { name: 'Ironpaw', element: 'Neutral', size: 'S', build: panda, note: 'A panda fighter in a low guard, fists up and wrapped, white qi burning off its shoulders.',
    parts: ['<b>Guard.</b> A low, wide stance on planted black legs, the right fist leading and the left held back at the chin, forearms wrapped in red, fists bound in cream with gold knuckle plates.', '<b>Qi.</b> Pale flames of qi rising off the shoulders and back along the top line, qi lines burning on the chest and forearms, a glow and sparks round each fist.', '<b>Face.</b> A heavy round head, black patches with slit eyes under a black brow, a snarl with fangs, and a red headband with a gold plate and two tails that stream behind.', '<b>Strike.</b> Its attack swings the lead arm up level and snaps the elbow straight into a punch; its ultimate throws a left and then a right.'] },
  owl: { name: 'Duskseer', element: 'Dark', size: 'S', build: owl, note: 'A horned owl of the night, stern under a V brow, a crest of shadow quills burning violet.',
    parts: ['<b>Face.</b> A pale heart-shaped disc, amber eyes under a stern black V brow, a hooked beak that opens, tall ear tufts tipped with violet; the head rests turned toward the camera, as an owl\'s does.', '<b>Crest.</b> Shadow quills fanned from crown to nape, violet with pale cores, the shape that says Dark from the side.', '<b>Plumage.</b> Near-black indigo on the back, a muted lavender breast of barred scale-feathers, wings folded down the sides with a violet crescent and rune lines on each, a short dark tail.', '<b>Stance.</b> Upright on short feathered legs, three hooked talons forward and one back, motes of starlight drifting round it.'] },
};

export const ORDER = ['emberwolf', 'tidefang', 'thornstag', 'stonemaul', 'wardshell', 'pyrewing', 'eagle', 'lion', 'elephant', 'panda', 'owl'];
